apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: priv-quarkus-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: priv-quarkus-sample
    app.kubernetes.io/part-of: priv-quarkus-sample
  name: priv-quarkus-sample
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: priv-quarkus-sample
status:
  loadBalancer: {}
